### ISSUE TITLE
Can't seem to test controllers on Ubuntu versions newer than 18.04, but cannot get the script working on 18.04

### ISSUE THREAD

**Issue by HongSense** [carpikes/ds4-tools#10]
So, testing the controllers with gamepadtester.com on Ubuntu 22 and 24 don't work for me because Chromium-browser detects/maps the triggers to the right analog, and vice-versa. Installed Ubuntu 18 and Chromium has the correct mapping, but I cannot get the script to run. If I run without "sudo", I get a "permission denied" message, but if I run with "sudo", I get the following:

```
sudo python3 ds4-calibration-tool.py 
Traceback (most recent call last):
  File "ds4-calibration-tool.py", line 3, in <module>
    import usb.core
ModuleNotFoundError: No module named 'usb'
```

I have spent SEVERAL hours attempting to figure this out myself, but have only found info stating that "pyusb" needs to be installed...it already is. Other people are reporting on the Console Repair Legion Facebook group that they have it all working well, but I've had nothing but issues, probably because I have no idea how the underlying framework functions (Python), and am just following the instructions verbatim.

Can anyone save me months of anguish trying to get this going and help out?

Thanks!

**Comment by HongSense** [comment]
Ok, well, I went looking through the comments again, on the Facebook group, and found @ngth82 had mentioned actually running the TERMINAL as root, and not the script command, and it now seems to launch the script with no errors.

My new problem is that gampad-tester.com is showing all DS4 controller analogs at exactly 0.00000; the problem is that on Windows 10 they show as drifting in Chrome, so testing on Ubuntu appears to be useless (at least through gamepadtester.com on Chromium) for me at the moment. The reason I'm using Linux is so that we have one station to calibrate AND test all controllers at once.

Any ideas what's going on with this or if there is another way to test the analogs (other than Steam)?....which I may just resort to because this has taken a lot of time so far already and I have no idea of other available avenues.

**Comment by carpikes** [comment]
Hi! I tried with a ubuntu 18.04 docker and these are the steps that seems working:
1) install dependencies
```bash
sudo apt install libusb-1.0-0-dev python3 python3-virtualenv git
```

2) clone and install python deps
```bash
git clone ...
cd ds4-tools

python3 -m virtualenv --python=python3 venv
. venv/bin/activate
pip install -r requirements.txt
```

3) run the program as root
```bash
cd ds4-tools

sudo su # elevate the whole environment to root
. venv/bin/activate # this after sudo su
python3 ds4-tool.py 
```

let me know if this works

**Comment by HongSense** [comment]
> Hi! I tried with a ubuntu 18.04 docker and these are the steps that seems working:
> 
> 1. install dependencies
> 
> ```shell
> sudo apt install libusb-1.0-0-dev python3 python3-virtualenv git
> ```
> 
> 2. clone and install python deps
> 
> ```shell
> git clone ...
> cd ds4-tools
> 
> python3 -m virtualenv --python=python3 venv
> . venv/bin/activate
> pip install -r requirements.txt
> ```
> 
> 3. run the program as root
> 
> ```shell
> cd ds4-tools
> 
> sudo su # elevate the whole environment to root
> . venv/bin/activate # this after sudo su
> python3 ds4-tool.py 
> ```
> 
> let me know if this works

Thanks so much for the detailed instructions. I really just tend to bumble around to solve issues, and don't actually know everything about anything, so it's super helpful when I get this sort of response. I know some about a lot of things, but that means I don't attempt to comprehend all about a subject, only what's necessary for my current goals.

Unforunately, that also means I spend a lot of time trying to figure out solutions, and this one just didn't seem to have an answer, considering Google changed the way Chromium-based browsers interpret/interact with gamepads (maybe just DS4), and that older versions of Ubuntu (which the Chromium-based browsers DO function properly on with gamepad-tester.com) gave me a hell of a time with your script, presumably because if Python 2.*.

I may give this a go soon, but so far I decided to resort to Ubuntu 22.04 (which your script works OOB with) and Steam (which was recently heavily overhauled, requiring a bit more time to figure out).

The only problem I'm not sure will be addressed with your solution, is the fact that gamepad-tester.com was showing all analogs at 0.0000 in Linux, even when they clearly had drift when testing on gamepad-tester.com on Windows 10 and the console....I don't understand that, yet. Appreciate your assistance!

**Comment by HongSense** [comment]
> Hi! I tried with a ubuntu 18.04 docker and these are the steps that seems working:
> 
> 1. install dependencies
> 
> ```shell
> sudo apt install libusb-1.0-0-dev python3 python3-virtualenv git
> ```
> 
> 2. clone and install python deps
> 
> ```shell
> git clone ...
> cd ds4-tools
> 
> python3 -m virtualenv --python=python3 venv
> . venv/bin/activate
> pip install -r requirements.txt
> ```
> 
> 3. run the program as root
> 
> ```shell
> cd ds4-tools
> 
> sudo su # elevate the whole environment to root
> . venv/bin/activate # this after sudo su
> python3 ds4-tool.py 
> ```
> 
> let me know if this works



> > So, testing the controllers with gamepadtester.com on Ubuntu 22 and 24 don't work for me because Chromium-browser detects/maps the triggers to the right analog, and vice-versa. Installed Ubuntu 18 and Chromium has the correct mapping, but I cannot get the script to run. If I run without "sudo", I get a "permission denied" message, but if I run with "sudo", I get the following:
> > ```
> > sudo python3 ds4-calibration-tool.py 
> > Traceback (most recent call last):
> >   File "ds4-calibration-tool.py", line 3, in <module>
> >     import usb.core
> > ModuleNotFoundError: No module named 'usb'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I have spent SEVERAL hours attempting to figure this out myself, but have only found info stating that "pyusb" needs to be installed...it already is. Other people are reporting on the Console Repair Legion Facebook group that they have it all working well, but I've had nothing but issues, probably because I have no idea how the underlying framework functions (Python), and am just following the instructions verbatim.
> > Can anyone save me months of anguish trying to get this going and help out?
> > Thanks!
> 
> Sounds like your issue is that you installed everything without elevated permissions (normal user) and then you want to run as an elevated user (sudo -> “root”)
> 
> remove it all.
> 
> Reinstall python using sudo, Install the plugins using sudo. run the script using sudo.
> 
> I’m using the latest Ubuntu release on a second machine for running the script to calibrate controllers in bulk.
> 
> Actual analog testing is done back in my windows machine with gamepad-tester just because I have my invoicing software there and I take notes.

Yeesh, thanks buddy, that worked!

**Comment by carpikes** [comment]
Have you tried to use Firefox instead of Chrome on ubuntu 22.04?

**Comment by qwertychouskie** [comment]
I use Firefox and https://hardwaretester.com/gamepad and I have no issues reading values.
