### ISSUE TITLE
cant open ds4-tool.py

### ISSUE THREAD

**Issue by mochaaaa11** [carpikes/ds4-tools#14]
after going into the directory when i type "ds4-tool.py info" it doesnt do anything, just goes to the next line. what do i do?

**Comment by ngth82** [comment]
Did you install python? This is a python script.

**Comment by Luiz-Batista-Neto** [comment]
I'm having a similar problem when i run ds4-tool.py info a window just blink in my screen and then closes.

**Comment by ngth82** [comment]
> I'm having a similar problem, when i run ds4-tool.py info a window just blink in my screen and then closes.

You need to start from a command window first.

**Comment by Luiz-Batista-Neto** [comment]
Hey thanks! much appreciated.
