### ISSUE TITLE
ModuleNotFoundError: No module named 'usb'

### ISSUE THREAD

**Issue by Luiz-Batista-Neto** [carpikes/ds4-tools#16]
Everytime i try to run either ds4-tool.py or ds4-calibration-tool.py it returns me this

(venv) PS C:\Users\******\Downloads\ds4-tools> python3 ds4-tool.py info
Traceback (most recent call last):
  File "C:\Users\luizb\Downloads\ds4-tools\ds4-tool.py", line 3, in <module>
    import usb.core
ModuleNotFoundError: No module named 'usb'

Things i already tried:
- run requirements.txt in a virtual environment and outside of it
- reinstalled python
- rolledback to Hidusb driver and installing the Winusb again

**Comment by Jacksoft** [comment]
Have you tried in Command Prompt instead of PowerShell?
Probably virtual enviroinment is limited.

**Comment by now-its-dark** [comment]
Hi, I'm having the exact same issue here-- I tried all those same steps. Identical result with PowerShell and with the standard Windows command prompt. Pip is satisfied that the correct versions of all dependencies are installed in the venv lib location, but the script fails to import usb.core.
Unfortunately I'm not experienced enough with Python to diagnose this & looking through various threads online didn't yield any clear path forward.

**Comment by yzh9865** [comment]
I have the same issue on M1 macos 13, I don't know how to fix it

**Comment by carpikes** [comment]
@yzh9865 consider using https://the.al/dualshock instead of the python scripts. It should work out-of-the-box on mac using google chrome.
