### ISSUE TITLE
God! Please help us! Make the same utility for dualsense!

### ISSUE THREAD

**Issue by ZhenyaKa** [carpikes/ds4-tools#19]
This tool so wonderful and make life simplier

**Comment by qwertychouskie** [comment]
The DS4 uses an MT3610, while the Dualsense uses the MT3616.  It seems as though Sony stuck pretty close to their tried-and-true chipset, which means the firmware is also likely to be similar.  If I had to guess, the same HID commands for calibrating likely exist, just perhaps with different addresses.

**Comment by carpikes** [comment]
done! let me know if it works :)

**Comment by ZhenyaKa** [comment]
> done! let me know if it works :)

it wrote Waiting for dualsense and at all
![image](https://github.com/carpikes/ds4-tools/assets/28926895/e8ac7859-dab9-4277-af8f-865cb3a95fc2)

**Comment by ZhenyaKa** [comment]
![image](https://github.com/carpikes/ds4-tools/assets/28926895/b1f05a03-63e8-487f-9c84-66d74839ab50)
another shows this

**Comment by der-andyman** [comment]
Been there, done that. You need to update the firmware of the controller in order for the error to go away. There is a windows tool provided by Sony to update the firmware.

**Comment by ZhenyaKa** [comment]
![image](https://github.com/carpikes/ds4-tools/assets/28926895/2d25ae9d-9f53-40c0-b203-fb4ad61654ae)
the same :(
