### ISSUE TITLE
Won't change status to permanent

### ISSUE THREAD

**Issue by shakangel** [carpikes/ds4-tools#20]
When I try to change the permanent/temporary status it won't change it and it appears with a value of 255. 

(venv) C:\Users\new user\Documents\PS4 Software\Controller DS4 Calibration\ds4-tools>python ds4-tool.py set-flash-mirror-status 0
Waiting for a DualShock 4...
Found a DualShock 4: vendorId=054c productId=09cc
Set to: permanent
Re-reading flash mirror status..
Changes in flash mirror are temporary: 255

**Comment by carpikes** [comment]
Can it be that.. this DS4 is a clone?

**Comment by shakangel** [comment]
Now that you mention it... I compared to another DS4 that I have here JDM 0.55 and they are very similar but it's definitely a clone... it uses Mediatek chip though... any thoughts? Same chip different firmware you guessing? I want to calibrate the L2/R2... any ideas?

**Comment by qwertychouskie** [comment]
> Now that you mention it... I compared to another DS4 that I have here JDM 0.55 and they are very similar but it's definitely a clone... it uses Mediatek chip though... any thoughts? Same chip different firmware you guessing? I want to calibrate the L2/R2... any ideas?

Which MediaTek chip does it use?  If it's a MT3610, then it's more likely a genuine controller, but just a different revision.  (The MT3610 appears to be a Sony-exclusive chip.)  If it's something else, then it's likely non-OEM.

**Comment by carpikes** [comment]
@shakangel If it's a clone, it has its own firmware totally different from the original one
