### ISSUE TITLE
Just a thanks and discussing Dualsense

### ISSUE THREAD

**Issue by Stry-Glitch** [carpikes/ds4-tools#22]
Hi, pretty new to GitHub sorry I know I should have private message you but I could not find anything like this on GitHub.

I've been using your tool for quit some time now and I must say, you truly saved me a ton of time, and helped me recalibrate atleast 250 controller so far.

There is no firmware available to reverse engineer the Dualsense yet from what you've said from another thread but since I'm quite handy with my tool and hand, should I help you in any way possible please let me know.

I also aknowledge that doing this on your free time might be boring, we can discuss a real counterpart for your effort.

Providing this tool without any cost is truly noble (beyond whatever you can imagine to me), I would gladly pay you for the same thing on DS to make it happening.

Once again, big cheer to both of you !

**Comment by der-andyman** [comment]
First of all, thank you. This is a very nice, little tool. 

I would like to join the "can you make a DualSense Version?" wish 😇

**Comment by carpikes** [comment]
done! let me know if it works
