### ISSUE TITLE
Creating and restoring a backup copy of the gamepad firmware

### ISSUE THREAD

**Issue by Gnidozz** [carpikes/ds4-tools#27]
As I understand it, using this utility I can take a snapshot of the data before making changes to the device’s firmware.
Using the command:
`python ds4-tool.py dump-flash FILE_NAME.bin`

But how can I restore this backup from a file?
Tell me the appropriate command, please.

**Comment by carpikes** [comment]
Unfortunately there is no command to load a dump :(
The `dump-flash` command was used only for debugging purposes.
