### ISSUE TITLE
DS5 Script: Controller in invalid state

### ISSUE THREAD

**Issue by der-andyman** [carpikes/ds4-tools#31]
Hi there, I was very happy to see that the tool now supports Dualsense Controllers (as a test, I know) and I have 3 Controllers here which I wanted to test this tool on. But, I can only get as far as in the picture down below. Do I need to make the same changes in Zadig to the Dualshock controller as for the DS4? 
![grafik](https://github.com/carpikes/ds4-tools/assets/13424417/2ef51418-a9da-4436-a72f-ac37615c8d73)

**Comment by der-andyman** [comment]
OK, I replaced the drivers with libUSB and now it "works". Out of 3 Controllers, one is now somewhat damaged, one could be calibrated and one gives me an error: 
![grafik](https://github.com/carpikes/ds4-tools/assets/13424417/158195a6-656f-4288-89fd-d1c2ee71132e)

The damaged one now has no rumble ... is this possible though a tool like this? Neither of the motors are now making any vibrations :/

**Comment by der-andyman** [comment]
A little bit of additional info. I used the sony tool "Firmware Updater for DualsenseTM wireless controller" and the firmware of the controller I get the error message with is 0282.
The one with now not working vibration is 0307.
And the one that worked just fine is 0402.

I will try to update the 0282 one and test again.

**Comment by der-andyman** [comment]
First of all, sorry for all the answers, but I guess you need some feedback, so I will just continue XD

I updated the firmware of the first DS Controller with previously Firmware 0282 to the latest, which as of today is 0458 and now the calibration worked. So it was the firmware, what resulted in the error message. 

I am now charging the 2nd controller without vibration, as the tool says the battery is low, then I will update this one too and hope the vibration is back.

**Comment by der-andyman** [comment]
Well, I got all problems sorted out and solved now. The flat battery caused the vibration not to work, so after charging the controller for a while, it now works. And the calibration seems to work as well, so i guess thats it. 

Thank you again for your great work.

**Comment by JIEgOKOJI** [comment]
Calibrated my dualsense with hall sensor analogs, Works aweasome now

**Comment by carpikes** [comment]
Good that you solved it!
