### ISSUE TITLE
Dualsense Instructions

### ISSUE THREAD

**Issue by Uniformly3576** [carpikes/ds4-tools#32]
Sorry I am quite a noobie.

Would there be any chance to add more detail instructions for the Dualsense calibration?

I seem to be able to see my controller with the script but center or range calibration does not seem to be making any difference.

My controller is on latest firmware and I installed Hall Effect sticks.

**Comment by Uniformly3576** [comment]
Thank you so much for this tool by the way!

**Comment by ivelweyz** [comment]
> Thank you! I know that python/zadig may be difficult to install. I'm working on a web-ui that calibrates the joystick without any installation (it just needs google chrome). Give it a try and let me know: https://the.al/dualshock/

Works great.

Both the scripts and the web ui app worked well for me on newest and slightly less new firmware.

**Comment by Uniformly3576** [comment]
Works amazingly! You are a wizard!

**Comment by carpikes** [comment]
Thank you!
