### ISSUE TITLE
DS5

### ISSUE THREAD

**Issue by nuadaxxx** [carpikes/ds4-tools#35]
Hi I have tried our tool now with many Dual Sense it works great, also with the newest firmware...

But I have seen sometimes that the range is not enough, maybe u can increase the range slightly...

i use hall effect sticks.

https://ibb.co/4PZ6DT1

**Comment by nuadaxxx** [comment]
Maybe u can add an + offset or something.. ???

**Comment by GittyUser54321** [comment]
> Maybe u can add a custom Range + offset or something.. ??? Like an offset for each direction that add this offset to the parsed one from your tool...
> 
> i think then the stick is the problem, but with a Manual/Custom/offset for each direction, it's possible to fit for every stick..

Thats not a bad idea. Like a +5-10% offset before applying to DS firmware.

**Comment by nuadaxxx** [comment]
> > Maybe u can add a custom Range + offset or something.. ??? Like an offset for each direction that add this offset to the parsed one from your tool...
> > i think then the stick is the problem, but with a Manual/Custom/offset for each direction, it's possible to fit for every stick..
> 
> Thats not a bad idea. Like a +5-10% offset before applying to DS firmware.

yes but for each direction because sometime is, too much at the top left or too less. and that is the issue for all directions.

Sometimes is top left too much and in same time bottom right to less... ect ect..

**Comment by GittyUser54321** [comment]
> > > Maybe u can add a custom Range + offset or something.. ??? Like an offset for each direction that add this offset to the parsed one from your tool...
> > > i think then the stick is the problem, but with a Manual/Custom/offset for each direction, it's possible to fit for every stick..
> > 
> > 
> > Thats not a bad idea. Like a +5-10% offset before applying to DS firmware.
> 
> yes but for each direction because sometime is, too much at the top left or too less. and that is the issue for all directions.
> 
> Sometimes is top left too much and in same time bottom right to less... ect ect..
> 
> That is way it needs for every direction + and - offset

Yeah for sure this could be coded into the program.

**Comment by carpikes** [comment]
I'm afraid to say that this cannot be done: the script can only send these messages to the controller:
- start sampling
- stop sampling and save

The firmware in the controller is responsible of sampling and save the calibration.

**Comment by ivelweyz** [comment]
The issue isn't the script but likely the stick itself or your install. The stick module itself might be just poorly calibrated from factory or it's not sitting perfectly flat against the pcb when you soldered it in. All these sticks are different.

Btw, how does one go about limiting the outer ranges when calibrating? In some spots, my range is quite a bit beyond the circle. Thanks.

**Comment by nuadaxxx** [comment]
> The issue isn't the script but likely the stick itself or your install. The stick module itself might be just poorly calibrated from factory or it's not sitting perfectly flat against the pcb when you soldered it in. All these sticks are different.
> 
> Btw, how does one go about limiting the outer ranges when calibrating? In some spots, my range is quite a bit beyond the circle. Thanks.

yes, with a manual calibrated hall stick and then calibrated with this tool, it works great.

https://ibb.co/fM3kMYZ

**Comment by carpikes** [comment]
Good to know!
