### ISSUE TITLE
ds4-tool.py makes reference to "ds4-util' in argument parser

### ISSUE THREAD

**Issue by ngth82** [carpikes/ds4-tools#7]
The argument parser makes a reference to "ds4-util" - change that to ds4-tool, or use arg 0.

```
parser = argparse.ArgumentParser(prog='ds4-util',
                                 description="Play with the DS4 controller",
                                 epilog="By the_al")
```

I suggest removing the prog='ds4-util' statement, then the argument parser will automatically fill in argv[0] for the file name. Less to maintain, should you want to change the filename (again) at a later date.

**Comment by carpikes** [comment]
Thanks! Will fix soon!

**Comment by carpikes** [comment]
Fixed, thank you!
